import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "CRUD de Usuários",
  description: "Generated by create next app",
};

import { QueryProvider } from '@/providers/QueryProvider'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body>
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  )
}
